version: 2.1

commands:
  fetch:
    steps:
      - checkout

  test_package:
    steps:
      - run: pip install pytest deepdiff inflection loguru
      - run: pip install --pre --index-url https://test.pypi.org/simple/ cvldoc_parser
      - run:
          name: Run tests
          command: |
            export PATH=~/repo/:$PATH
            cd tests
            pytest -v -rA

  upgrade_pip:
    steps:
      - run: python -m pip install --user --upgrade pip
      - run: pip install -U pip setuptools

jobs:
  build:
    docker:
      - image: &img cimg/python:3.8
    working_directory: ~/repo
    steps:
      - fetch
      - upgrade_pip
      - run:
          name: Install dependencies
          command: pip install --user twine wheel
      - run:
          name: Build
          command: python setup.py sdist bdist_wheel
      - test_package
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  upload_staging:
    docker:
      - image: *img
    resource_class: small
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - upgrade_pip
      - run:
          name: Upload to test PyPi
          command: |
            pip install --user twine
            python -m twine upload --verbose --repository testpypi -u ${TESTPYPI_USER} -p ${TESTPYPI_PASSWORD} dist/*

  upload_prod:
    docker:
      - image: *img
    resource_class: small
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - upgrade_pip
      - run:
          name: Upload to prod PyPi
          command: |
            pip install --user twine
            python -m twine upload --verbose -u ${PRODPYPI_USER} -p ${PRODPYPI_PASSWORD} dist/*

  test_staging:
    docker:
      - image: *img
    resource_class: small
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - upgrade_pip
      - run:
          name: Delay before testing new version
          command: sleep 90
      - run:
          name: Install newly-uploaded version from TestPyPI
          command: |
            pip --version
            pip install --pre --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple CVLDoc
            pip freeze
      - run:
          name: Check `cvldoc --help`
          command: cvldoc --help
      - run:
          name: Run CVLDoc on a test file
          command: sh tests/run_single_test.sh 

  python_lint:
    docker:
      - image: *img
    resource_class: small
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - upgrade_pip
      - run: pip install --user black
      - run: python -m black .


parameters:
  publish:
    default: false
    type: boolean


workflows:
  test-build:
    jobs:
      - build
      - python_lint:
          requires:
            - build

  build-and-publish:
    when: << pipeline.parameters.publish >>
    jobs:
      - build
      - python_lint:
          requires:
            - build
      - upload_staging:
          requires:
            - build
            - python_lint
      - test_staging:
          requires:
            - upload_staging
      - upload_prod:
          requires:
            - test_staging
          filters:
            branches:
              only:
                - /production.*/