version: 2.1

jobs:
  build:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Install pip"
          command: |
            python3 --version
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python3 get-pip.py
      - run:
          name: "Install pip dependencies"
          command: "pip install wheel twine"
      - run:
          name: "Build wheel"
          command: "python3 setup.py bdist_wheel"
      - run:
          name: "Build source distribution"
          command: "python3 setup.py sdist"
      - run:
          name: "Publish to PyPI"
          command: "echo publish"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-publish-python-package:
    jobs:
      - build
