version: 2.1

jobs:
  test-and-build:
    docker:
      - image: cimg/python:3.7.13
    steps:
      - checkout
      - run:
          name: "Install pip dependencies"
          command: |
            pip install wheel pytest deepdiff inflection
            pip install -i https://test.pypi.org/simple/ cvldoc_parser==0.5.0
      - run:
          name: "run tests"
          command: |
            cd tests
            pytest natspec_tests.py
      - run:
          name: "Build wheel and source"
          command: |
            python3 setup.py bdist_wheel sdist
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - ./dist

  publish-to-test-pypi:
    docker:
      - image: cimg/python:3.7.13
    steps:
      - attach_workspace:
         at: .
      - run:
          name: Upload to PyPI
          command: |
            pip install --user twine
            python3 -m twine upload --skip-existing --verbose --repository testpypi -u ${TESTPYPI_USER} -p ${TESTPYPI_PASSWORD} dist/*

  publish-to-production-pypi:
    docker:
      - image: cimg/python:3.7.13
    steps:
      - attach_workspace:
         at: .
      - run:
          name: Upload to PyPI
          command: |
            pip install --user twine
            python3 -m twine upload --skip-existing --verbose -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*

workflows:
  test-build-and-publish:
    jobs:
      - test-and-build
      - publish-to-test-pypi:
          requires:
            - test-and-build
      - publish-to-production-pypi:
          requires:
            - test-and-build
          filters:
            branches:
              only: production