version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7.13
    steps:
      - checkout
      - run:
          name: "Install pip dependencies"
          command: "pip install wheel twine bin/natspec_parser-0.2.0-cp37-cp37m-manylinux_2_28_x86_64.whl"
      - run:
          name: "Build wheel and source"
          command: "python3 setup.py bdist_wheel sdist"
      - store_artifacts:
          path: /workspaces/natspecTools/dist

workflows:
  build-and-publish-python-package:
    jobs:
      - build
      